tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                  "#005ab4",
        "on-primary":               "#ffffff",
        "primary-container":        "#0a73e0",
        "on-primary-container":     "#fefcff",
        "primary-fixed":            "#d6e3ff",
        "primary-fixed-dim":        "#aac7ff",
        "on-primary-fixed":         "#001b3e",
        "on-primary-fixed-variant": "#00458d",
        "secondary":                "#465f88",
        "on-secondary":             "#ffffff",
        "secondary-container":      "#b6d0ff",
        "on-secondary-container":   "#3f5881",
        "secondary-fixed":          "#d6e3ff",
        "secondary-fixed-dim":      "#aec7f7",
        "on-secondary-fixed":       "#001b3d",
        "on-secondary-fixed-variant":"#2d476f",
        "tertiary":                 "#964400",
        "on-tertiary":              "#ffffff",
        "tertiary-container":       "#bd5700",
        "on-tertiary-container":    "#fffbff",
        "tertiary-fixed":           "#ffdbc9",
        "tertiary-fixed-dim":       "#ffb68c",
        "on-tertiary-fixed":        "#321200",
        "on-tertiary-fixed-variant":"#763400",
        "error":                    "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        "background":               "#f9f9ff",
        "on-background":            "#181c22",
        "surface":                  "#f9f9ff",
        "on-surface":               "#181c22",
        "surface-variant":          "#e0e2eb",
        "on-surface-variant":       "#414753",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f1f3fc",
        "surface-container":        "#ebedf7",
        "surface-container-high":   "#e6e8f1",
        "surface-container-highest":"#e0e2eb",
        "surface-dim":              "#d7dae3",
        "surface-bright":           "#f9f9ff",
        "surface-tint":             "#005db8",
        "inverse-surface":          "#2d3037",
        "inverse-on-surface":       "#eef0fa",
        "inverse-primary":          "#aac7ff",
        "outline":                  "#717785",
        "outline-variant":          "#c1c6d5",
      },
      borderRadius: { DEFAULT:"0.25rem", lg:"0.5rem", xl:"0.75rem", full:"9999px" },
      spacing: { xs:"4px", sm:"8px", base:"8px", md:"16px", lg:"24px", xl:"32px" },
      fontFamily: { sans:["Inter","sans-serif"] },
      fontSize: {
        "label-sm":  ["12px",{lineHeight:"16px",fontWeight:"500"}],
        "label-md":  ["14px",{lineHeight:"20px",fontWeight:"500"}],
        "label-lg":  ["16px",{lineHeight:"24px",fontWeight:"500"}],
        "body-sm":   ["12px",{lineHeight:"16px",fontWeight:"400"}],
        "body-md":   ["16px",{lineHeight:"24px",fontWeight:"400"}],
        "title-sm":  ["14px",{lineHeight:"20px",fontWeight:"500"}],
        "title-md":  ["16px",{lineHeight:"24px",fontWeight:"500"}],
        "title-lg":  ["22px",{lineHeight:"28px",fontWeight:"400"}],
        "headline-sm":["24px",{lineHeight:"32px",fontWeight:"400"}],
        "headline-md":["28px",{lineHeight:"36px",fontWeight:"400"}],
        "headline-lg":["32px",{lineHeight:"40px",fontWeight:"400"}],
        "display-sm": ["36px",{lineHeight:"44px",fontWeight:"400"}],
      }
    }
  }
};
